import { PINGENTE_IMAGES } from '../assets/pingentes';
import { ANEIS_IMAGES } from '../assets/aneis';
import { BRINCOS } from '../assets/brincos';
import { PULSEIRAS } from '../assets/pulseiras';
import { CONJUNTOS } from '../assets/conjuntos';

export const FEMALE_PRODUCTS_DATA = {
  aneis: [
    { name: 'Anel Coração', price: 55.90, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[0] },
    { name: 'Anel Elo', price: 60.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[1] },
    { name: 'Anel Dourado', price: 65.50, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[2] },
    { name: 'Anel Pedra', price: 70.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[3] },
    { name: 'Anel Estrela', price: 72.80, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[4] },
    { name: 'Anel Gota', price: 80.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[5] },
    { name: 'Anel Oval', price: 85.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[6] },
    { name: 'Anel Quadrado', price: 90.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[7] },
    { name: 'Anel Prateado', price: 95.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[8] },
    { name: 'Anel Sol', price: 100.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[9] },
    { name: 'Anel Lua', price: 105.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[10] },
    { name: 'Anel Olho Grego', price: 110.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[11] },
    { name: 'Anel Infinito', price: 115.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[12] },
    { name: 'Anel Árvore', price: 120.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[13] },
    { name: 'Anel Asas', price: 125.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[14] },
    { name: 'Anel Chave', price: 130.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[15] },
    { name: 'Anel Floral', price: 135.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[16] },
    { name: 'Anel Geométrico', price: 140.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[17] },
    { name: 'Anel Coroa', price: 145.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[18] },
    { name: 'Anel Âncora', price: 150.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[19] },
    { name: 'Anel Flecha', price: 155.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[20] },
    { name: 'Anel Pássaro', price: 160.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[21] },
    { name: 'Anel Coração Vazio', price: 165.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[22] },
    { name: 'Anel Clássico', price: 99.90, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[23] },
    { name: 'Anel Moderno', price: 105.90, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[24] },
  ],
  brincos: [
    { name: 'Brinco 1', price: 39.90, category: 'brincos', gender: 'feminina', image: BRINCOS[0] },
    { name: 'Brinco 2', price: 42.00, category: 'brincos', gender: 'feminina', image: BRINCOS[1] },
    { name: 'Brinco 3', price: 45.50, category: 'brincos', gender: 'feminina', image: BRINCOS[2] },
    { name: 'Brinco 4', price: 48.90, category: 'brincos', gender: 'feminina', image: BRINCOS[3] },
    { name: 'Brinco 5', price: 51.00, category: 'brincos', gender: 'feminina', image: BRINCOS[4] },
    { name: 'Brinco 6', price: 54.00, category: 'brincos', gender: 'feminina', image: BRINCOS[5] },
    { name: 'Brinco 7', price: 57.50, category: 'brincos', gender: 'feminina', image: BRINCOS[6] },
    { name: 'Brinco 8', price: 60.00, category: 'brincos', gender: 'feminina', image: BRINCOS[7] },
    { name: 'Brinco 9', price: 63.20, category: 'brincos', gender: 'feminina', image: BRINCOS[8] },
    { name: 'Brinco 10', price: 66.00, category: 'brincos', gender: 'feminina', image: BRINCOS[9] },
    { name: 'Brinco 11', price: 69.90, category: 'brincos', gender: 'feminina', image: BRINCOS[10] },
    { name: 'Brinco 12', price: 72.50, category: 'brincos', gender: 'feminina', image: BRINCOS[11] },
    { name: 'Brinco 13', price: 75.00, category: 'brincos', gender: 'feminina', image: BRINCOS[12] },
    { name: 'Brinco 14', price: 78.00, category: 'brincos', gender: 'feminina', image: BRINCOS[13] },
    { name: 'Brinco 15', price: 81.50, category: 'brincos', gender: 'feminina', image: BRINCOS[14] },
    { name: 'Brinco 16', price: 84.00, category: 'brincos', gender: 'feminina', image: BRINCOS[15] },
    { name: 'Brinco 17', price: 87.00, category: 'brincos', gender: 'feminina', image: BRINCOS[16] },
    { name: 'Brinco 18', price: 90.00, category: 'brincos', gender: 'feminina', image: BRINCOS[17] },
    { name: 'Brinco 19', price: 93.50, category: 'brincos', gender: 'feminina', image: BRINCOS[18] },
    { name: 'Brinco 20', price: 96.00, category: 'brincos', gender: 'feminina', image: BRINCOS[19] },
    { name: 'Brinco 21', price: 99.00, category: 'brincos', gender: 'feminina', image: BRINCOS[20] },
    { name: 'Brinco 22', price: 102.50, category: 'brincos', gender: 'feminina', image: BRINCOS[21] },
    { name: 'Brinco 23', price: 105.00, category: 'brincos', gender: 'feminina', image: BRINCOS[22] },
  ],
  argolas: [
    { name: 'Argola Dourada Média', price: 59.90, category: 'argolas', gender: 'feminina', image: 'https://via.placeholder.com/200' },
    { name: 'Argola Prateada Pequena', price: 49.90, category: 'argolas', gender: 'feminina', image: 'https://via.placeholder.com/200' },
  ],
    conjuntos: [
    { name: 'Conjunto 1', price: 39.90, category: 'conjuntos', gender: 'feminina', image: CONJUNTOS[0] },
    { name: 'Conjunto 2', price: 42.00, category: 'conjuntos', gender: 'feminina', image: CONJUNTOS[1] },
    { name: 'Conjunto 3', price: 45.50, category: 'conjuntos', gender: 'feminina', image: CONJUNTOS[2] },
    { name: 'Conjunto 4', price: 48.90, category: 'conjuntos', gender: 'feminina', image: CONJUNTOS[3] },

  ],
  correntes: [
    { name: 'Corrente Elo', price: 99.90, category: 'correntes', gender: 'feminina', image: 'https://via.placeholder.com/200' },
    { name: 'Corrente Grumet', price: 109.90, category: 'correntes', gender: 'feminina', image: 'https://via.placeholder.com/200' },
  ],
  pulseiras: [
    { name: 'Pulseira 1', price: 39.90, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[0] },
    { name: 'Pulseira 2', price: 42.00, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[1] },
    { name: 'Pulseira 3', price: 45.50, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[2] },
    { name: 'Pulseira 4', price: 48.90, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[3] },
    { name: 'Pulseira 5', price: 51.00, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[4] },
    { name: 'Pulseira 6', price: 54.00, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[5] },
    { name: 'Pulseira 7', price: 57.50, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[6] },
    { name: 'Pulseira 8', price: 60.00, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[7] },
    { name: 'Pulseira 9', price: 63.20, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[8] },
    { name: 'Pulseira 10', price: 66.00, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[9] },
    { name: 'Pulseira 11', price: 69.90, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[10] },
    { name: 'Pulseira 12', price: 72.50, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[11] },
    { name: 'Pulseira 13', price: 75.00, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[12] },
    { name: 'Pulseira 14', price: 78.00, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[13] },
    { name: 'Pulseira 15', price: 81.50, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[14] },
    { name: 'Pulseira 16', price: 84.00, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[15] },
    { name: 'Pulseira 17', price: 87.00, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[16] },
    { name: 'Pulseira 18', price: 90.00, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[17] },
    { name: 'Pulseira 19', price: 93.50, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[18] },
    { name: 'Pulseira 20', price: 96.00, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[19] },
  ],
  pingentes: [
    { name: 'Pingente de Cruz', price: 39.90, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[0] },
    { name: 'Pingente de Letra', price: 45.90, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[1] },
    { name: 'Pingente Coração', price: 55.90, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[2] },
    { name: 'Pingente Corrente', price: 60.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[3] },
    { name: 'Pingente Dourado', price: 65.50, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[4] },
    { name: 'Pingente Pedra', price: 70.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[5] },
    { name: 'Pingente Estrela', price: 72.80, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[6] },
    { name: 'Pingente Gota', price: 80.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[7] },
    { name: 'Pingente Oval', price: 85.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[8] },
    { name: 'Pingente Quadrado', price: 90.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[9] },
    { name: 'Pingente Prateado', price: 95.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[10] },
    { name: 'Pingente Sol', price: 100.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[11] },
    { name: 'Pingente Lua', price: 105.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[12] },
    { name: 'Pingente Olho Grego', price: 110.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[13] },
    { name: 'Pingente Infinito', price: 115.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[14] },
    { name: 'Pingente Árvore', price: 120.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[15] },
    { name: 'Pingente Asas', price: 125.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[16] },
    { name: 'Pingente Chave', price: 130.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[17] },
    { name: 'Pingente Floral', price: 135.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[18] },
    { name: 'Pingente Geométrico', price: 140.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[19] },
    { name: 'Pingente Coroa', price: 145.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[20] },
    { name: 'Pingente Âncora', price: 150.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[21] },
    { name: 'Pingente Flecha', price: 155.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[22] },
    { name: 'Pingente Pássaro', price: 160.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[23] },
    { name: 'Pingente Coração Vazio', price: 165.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[24] },
  ],
};