import { PINGENTE_IMAGES } from '../assets/pingentes';
import { ANEIS_IMAGES } from '../assets/aneis';
import { BRINCOS } from '../assets/brincos-e-argolas';
import { PULSEIRAS } from '../assets/pulseiras';
import { CONJUNTOS } from '../assets/conjuntos';
import { COLARES } from '../assets/colares';

export const FEMALE_PRODUCTS_DATA = {
  aneis: [
    { name: 'Anel Coração', price: 55.90, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[0] },
    { name: 'Anel Elo', price: 60.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[1] },
    { name: 'Anel Dourado', price: 65.50, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[2] },
    { name: 'Anel Pedra', price: 70.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[3] },
    { name: 'Anel Estrela', price: 72.80, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[4] },
    { name: 'Anel Gota', price: 80.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[5] },
    { name: 'Anel Oval', price: 85.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[6] },
    { name: 'Anel Quadrado', price: 90.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[7] },
    { name: 'Anel Prateado', price: 95.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[8] },
    { name: 'Anel Sol', price: 100.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[9] },
    { name: 'Anel Lua', price: 105.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[10] },
    { name: 'Anel Olho Grego', price: 110.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[11] },
    { name: 'Anel Infinito', price: 115.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[12] },
    { name: 'Anel Árvore', price: 120.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[13] },
    { name: 'Anel Asas', price: 125.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[14] },
    { name: 'Anel Chave', price: 130.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[15] },
    { name: 'Anel Floral', price: 135.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[16] },
    { name: 'Anel Geométrico', price: 140.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[17] },
    { name: 'Anel Coroa', price: 145.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[18] },
    { name: 'Anel Âncora', price: 150.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[19] },
    { name: 'Anel Flecha', price: 155.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[20] },
    { name: 'Anel Pássaro', price: 160.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[21] },
    { name: 'Anel Coração Vazio', price: 165.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[22] },
    { name: 'Anel Clássico', price: 99.90, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[23] },
    { name: 'Anel Moderno', price: 105.90, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[24] },
  ],
  "brincos e argolas": [
    { name: 'Brinco 1', price: 39.90, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[0] },
    { name: 'Brinco 2', price: 42.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[1] },
    { name: 'Brinco 3', price: 45.50, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[2] },
    { name: 'Brinco 4', price: 48.90, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[3] },
    { name: 'Brinco 5', price: 51.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[4] },
    { name: 'Brinco 6', price: 54.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[5] },
    { name: 'Brinco 7', price: 57.50, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[6] },
    { name: 'Brinco 8', price: 60.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[7] },
    { name: 'Brinco 9', price: 63.20, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[8] },
    { name: 'Brinco 10', price: 66.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[9] },
    { name: 'Brinco 11', price: 69.90, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[10] },
    { name: 'Brinco 12', price: 72.50, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[11] },
    { name: 'Brinco 13', price: 75.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[12] },
    { name: 'Brinco 14', price: 78.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[13] },
    { name: 'Brinco 15', price: 81.50, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[14] },
    { name: 'Brinco 16', price: 84.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[15] },
    { name: 'Brinco 17', price: 87.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[16] },
    { name: 'Brinco 18', price: 90.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[17] },
    { name: 'Brinco 19', price: 93.50, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[18] },
    { name: 'Brinco 20', price: 96.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[19] },
    { name: 'Brinco 21', price: 99.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[20] },
    { name: 'Brinco 22', price: 102.50, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[21] },
    { name: 'Brinco 23', price: 105.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[22] },
    { name: 'Brinco 24', price: 108.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[23] },
    { name: 'Brinco 25', price: 111.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[24] },
    { name: 'Brinco 26', price: 114.50, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[25] },
    { name: 'Brinco 27', price: 117.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[26] },
    { name: 'Brinco 28', price: 120.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[27] },
    { name: 'Brinco 29', price: 123.50, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[28] },
    { name: 'Brinco 30', price: 126.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[29] },
    { name: 'Brinco 31', price: 129.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[30] },
    { name: 'Brinco 32', price: 132.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[31] },
    { name: 'Brinco 33', price: 135.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[32] },
    { name: 'Brinco 34', price: 138.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[33] },
    { name: 'Brinco 35', price: 141.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[34] },
    { name: 'Brinco 36', price: 144.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[35] },
    { name: 'Brinco 37', price: 147.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[36] },
    { name: 'Brinco 38', price: 150.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[37] },
    { name: 'Brinco 39', price: 153.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[38] },
    { name: 'Brinco 40', price: 156.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[39] },
    { name: 'Brinco 41', price: 159.00, category: 'brincos e argolas', gender: 'feminina', image: BRINCOS[40] },
  ],
  conjuntos: [
    { name: 'Conjunto 1', price: 39.90, category: 'conjuntos', gender: 'feminina', image: CONJUNTOS[0] },
    { name: 'Conjunto 2', price: 42.00, category: 'conjuntos', gender: 'feminina', image: CONJUNTOS[1] },
    { name: 'Conjunto 3', price: 45.50, category: 'conjuntos', gender: 'feminina', image: CONJUNTOS[2] },
    { name: 'Conjunto 4', price: 48.90, category: 'conjuntos', gender: 'feminina', image: CONJUNTOS[3] },

  ],
  colares: [
    { name: 'Colar 1', price: 39.90, category: 'colares', gender: 'feminina', image: COLARES[0] },
    { name: 'Colar 2', price: 42.00, category: 'colares', gender: 'feminina', image: COLARES[1] },
    { name: 'Colar 3', price: 45.50, category: 'colares', gender: 'feminina', image: COLARES[2] },
    { name: 'Colar 4', price: 48.90, category: 'colares', gender: 'feminina', image: COLARES[3] },
    { name: 'Colar 5', price: 51.00, category: 'colares', gender: 'feminina', image: COLARES[4] },
    { name: 'Colar 6', price: 54.00, category: 'colares', gender: 'feminina', image: COLARES[5] },
    { name: 'Colar 7', price: 57.50, category: 'colares', gender: 'feminina', image: COLARES[6] },
    { name: 'Colar 8', price: 60.00, category: 'colares', gender: 'feminina', image: COLARES[7] },
    { name: 'Colar 9', price: 63.20, category: 'colares', gender: 'feminina', image: COLARES[8] },
    { name: 'Colar 10', price: 66.00, category: 'colares', gender: 'feminina', image: COLARES[9] },
    { name: 'Colar 11', price: 69.90, category: 'colares', gender: 'feminina', image: COLARES[10] },
    { name: 'Colar 12', price: 72.50, category: 'colares', gender: 'feminina', image: COLARES[11] },
    { name: 'Colar 13', price: 75.00, category: 'colares', gender: 'feminina', image: COLARES[12] },
    { name: 'Colar 14', price: 78.00, category: 'colares', gender: 'feminina', image: COLARES[13] },
    { name: 'Colar 15', price: 81.50, category: 'colares', gender: 'feminina', image: COLARES[14] },
    { name: 'Colar 16', price: 84.00, category: 'colares', gender: 'feminina', image: COLARES[15] },
    { name: 'Colar 17', price: 87.00, category: 'colares', gender: 'feminina', image: COLARES[16] },
    { name: 'Colar 18', price: 90.00, category: 'colares', gender: 'feminina', image: COLARES[17] },
    { name: 'Colar 19', price: 93.50, category: 'colares', gender: 'feminina', image: COLARES[18] },
    { name: 'Colar 20', price: 96.00, category: 'colares', gender: 'feminina', image: COLARES[19] },
    { name: 'Colar 21', price: 99.00, category: 'colares', gender: 'feminina', image: COLARES[20] },
    { name: 'Colar 22', price: 102.50, category: 'colares', gender: 'feminina', image: COLARES[21] },
    { name: 'Colar 23', price: 105.00, category: 'colares', gender: 'feminina', image: COLARES[22] },
    { name: 'Colar 24', price: 108.00, category: 'colares', gender: 'feminina', image: COLARES[23] },
    { name: 'Colar 25', price: 111.00, category: 'colares', gender: 'feminina', image: COLARES[24] }
  ],
  pulseiras: [
    { name: 'Pulseira 1', price: 39.90, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[0] },
    { name: 'Pulseira 2', price: 42.00, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[1] },
    { name: 'Pulseira 3', price: 45.50, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[2] },
    { name: 'Pulseira 4', price: 48.90, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[3] },
    { name: 'Pulseira 5', price: 51.00, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[4] },
    { name: 'Pulseira 6', price: 54.00, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[5] },
    { name: 'Pulseira 7', price: 57.50, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[6] },
    { name: 'Pulseira 8', price: 60.00, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[7] },
    { name: 'Pulseira 9', price: 63.20, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[8] },
    { name: 'Pulseira 10', price: 66.00, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[9] },
    { name: 'Pulseira 11', price: 69.90, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[10] },
    { name: 'Pulseira 12', price: 72.50, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[11] },
    { name: 'Pulseira 13', price: 75.00, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[12] },
    { name: 'Pulseira 14', price: 78.00, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[13] },
    { name: 'Pulseira 15', price: 81.50, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[14] },
    { name: 'Pulseira 16', price: 84.00, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[15] },
    { name: 'Pulseira 17', price: 87.00, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[16] },
    { name: 'Pulseira 18', price: 90.00, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[17] },
    { name: 'Pulseira 19', price: 93.50, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[18] },
    { name: 'Pulseira 20', price: 96.00, category: 'pulseiras', gender: 'feminina', image: PULSEIRAS[19] },
  ],
  pingentes: [
    { name: 'Pingente de Cruz', price: 39.90, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[0] },
    { name: 'Pingente de Letra', price: 45.90, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[1] },
    { name: 'Pingente Coração', price: 55.90, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[2] },
    { name: 'Pingente Corrente', price: 60.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[3] },
    { name: 'Pingente Dourado', price: 65.50, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[4] },
    { name: 'Pingente Pedra', price: 70.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[5] },
    { name: 'Pingente Estrela', price: 72.80, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[6] },
    { name: 'Pingente Gota', price: 80.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[7] },
    { name: 'Pingente Oval', price: 85.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[8] },
    { name: 'Pingente Quadrado', price: 90.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[9] },
    { name: 'Pingente Prateado', price: 95.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[10] },
    { name: 'Pingente Sol', price: 100.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[11] },
    { name: 'Pingente Lua', price: 105.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[12] },
    { name: 'Pingente Olho Grego', price: 110.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[13] },
    { name: 'Pingente Infinito', price: 115.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[14] },
    { name: 'Pingente Árvore', price: 120.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[15] },
    { name: 'Pingente Asas', price: 125.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[16] },
    { name: 'Pingente Chave', price: 130.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[17] },
    { name: 'Pingente Floral', price: 135.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[18] },
  ],
};