import { PINGENTE_IMAGES } from '../assets/pingentes';
import { ANEIS_IMAGES } from '../assets/aneis';
import { BRINCOS_E_ARGOLAS_IMAGES } from '../assets/conjuntos';

export const FEMALE_PRODUCTS_DATA = {
  aneis: [
    { name: 'Anel Coração', price: 55.90, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[0] },
    { name: 'Anel Elo', price: 60.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[1] },
    { name: 'Anel Dourado', price: 65.50, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[2] },
    { name: 'Anel Pedra', price: 70.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[3] },
    { name: 'Anel Estrela', price: 72.80, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[4] },
    { name: 'Anel Gota', price: 80.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[5] },
    { name: 'Anel Oval', price: 85.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[6] },
    { name: 'Anel Quadrado', price: 90.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[7] },
    { name: 'Anel Prateado', price: 95.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[8] },
    { name: 'Anel Sol', price: 100.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[9] },
    { name: 'Anel Lua', price: 105.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[10] },
    { name: 'Anel Olho Grego', price: 110.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[11] },
    { name: 'Anel Infinito', price: 115.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[12] },
    { name: 'Anel Árvore', price: 120.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[13] },
    { name: 'Anel Asas', price: 125.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[14] },
    { name: 'Anel Chave', price: 130.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[15] },
    { name: 'Anel Floral', price: 135.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[16] },
    { name: 'Anel Geométrico', price: 140.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[17] },
    { name: 'Anel Coroa', price: 145.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[18] },
    { name: 'Anel Âncora', price: 150.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[19] },
    { name: 'Anel Flecha', price: 155.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[20] },
    { name: 'Anel Pássaro', price: 160.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[21] },
    { name: 'Anel Coração Vazio', price: 165.00, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[22] },
    { name: 'Anel Clássico', price: 99.90, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[23] },
    { name: 'Anel Moderno', price: 105.90, category: 'aneis', gender: 'feminina', image: ANEIS_IMAGES[24] },
  ],
  brincos: [
    { name: 'Brinco de Pérola', price: 39.90, category: 'brincos', gender: 'feminina', image: 'https://via.placeholder.com/200' },
    { name: 'Brinco Ponto de Luz', price: 49.90, category: 'brincos', gender: 'feminina', image: 'https://via.placeholder.com/200' },
  ],
  argolas: [
    { name: 'Argola Dourada Média', price: 59.90, category: 'argolas', gender: 'feminina', image: 'https://via.placeholder.com/200' },
    { name: 'Argola Prateada Pequena', price: 49.90, category: 'argolas', gender: 'feminina', image: 'https://via.placeholder.com/200' },
  ],
    conjuntos: [
    { name: 'Conjunto 1', price: 129.90, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[0] },
    { name: 'Conjunto 2', price: 149.90, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[1] },
    { name: 'Conjunto 3', price: 110.50, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[2] },
    { name: 'Conjunto 4', price: 115.00, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[3] },
    { name: 'Conjunto 5', price: 120.00, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[4] },
    { name: 'Conjunto 6', price: 130.00, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[5] },
    { name: 'Conjunto 7', price: 135.00, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[6] },
    { name: 'Conjunto 8', price: 140.00, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[7] },
    { name: 'Conjunto 9', price: 145.00, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[8] },
    { name: 'Conjunto 10', price: 150.00, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[9] },
    { name: 'Conjunto 11', price: 155.00, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[10] },
    { name: 'Conjunto 12', price: 160.00, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[11] },
    { name: 'Conjunto 13', price: 165.00, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[12] },
    { name: 'Conjunto 14', price: 170.00, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[13] },
    { name: 'Conjunto 15', price: 175.00, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[14] },
    { name: 'Conjunto 16', price: 180.00, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[15] },
    { name: 'Conjunto 17', price: 185.00, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[16] },
    { name: 'Conjunto 18', price: 190.00, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[17] },
    { name: 'Conjunto 19', price: 195.00, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[18] },
    { name: 'Conjunto 20', price: 200.00, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[19] },
    { name: 'Conjunto 21', price: 205.00, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[20] },
    { name: 'Conjunto 22', price: 210.00, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[21] },
    { name: 'Conjunto 23', price: 215.00, category: 'conjuntos', gender: 'feminina', image: BRINCOS_E_ARGOLAS_IMAGES[22] },
  ],
  correntes: [
    { name: 'Corrente Elo', price: 99.90, category: 'correntes', gender: 'feminina', image: 'https://via.placeholder.com/200' },
    { name: 'Corrente Grumet', price: 109.90, category: 'correntes', gender: 'feminina', image: 'https://via.placeholder.com/200' },
  ],
  pulseiras: [
    { name: 'Pulseira Bolinha', price: 69.90, category: 'pulseiras', gender: 'feminina', image: 'https://via.placeholder.com/200' },
    { name: 'Pulseira Malha', price: 79.90, category: 'pulseiras', gender: 'feminina', image: 'https://via.placeholder.com/200' },
  ],
  pingentes: [
    { name: 'Pingente de Cruz', price: 39.90, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[0] },
    { name: 'Pingente de Letra', price: 45.90, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[1] },
    { name: 'Pingente Coração', price: 55.90, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[2] },
    { name: 'Pingente Corrente', price: 60.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[3] },
    { name: 'Pingente Dourado', price: 65.50, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[4] },
    { name: 'Pingente Pedra', price: 70.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[5] },
    { name: 'Pingente Estrela', price: 72.80, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[6] },
    { name: 'Pingente Gota', price: 80.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[7] },
    { name: 'Pingente Oval', price: 85.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[8] },
    { name: 'Pingente Quadrado', price: 90.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[9] },
    { name: 'Pingente Prateado', price: 95.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[10] },
    { name: 'Pingente Sol', price: 100.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[11] },
    { name: 'Pingente Lua', price: 105.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[12] },
    { name: 'Pingente Olho Grego', price: 110.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[13] },
    { name: 'Pingente Infinito', price: 115.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[14] },
    { name: 'Pingente Árvore', price: 120.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[15] },
    { name: 'Pingente Asas', price: 125.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[16] },
    { name: 'Pingente Chave', price: 130.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[17] },
    { name: 'Pingente Floral', price: 135.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[18] },
    { name: 'Pingente Geométrico', price: 140.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[19] },
    { name: 'Pingente Coroa', price: 145.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[20] },
    { name: 'Pingente Âncora', price: 150.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[21] },
    { name: 'Pingente Flecha', price: 155.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[22] },
    { name: 'Pingente Pássaro', price: 160.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[23] },
    { name: 'Pingente Coração Vazio', price: 165.00, category: 'pingentes', gender: 'feminina', image: PINGENTE_IMAGES[24] },
  ],
};